[2017-09-23 01:48:31] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-09-23 01:54:03] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServer.php\",\"line\":132,\"trace\":[{\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php\",\"line\":136,\"function\":\"isRunning\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServer\",\"type\":\"->\"}],\"count\":1})"} []
[2017-09-23 01:54:17] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 01:54:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 01:54:17] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"198c55","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/198c55","method":"GET"} []
[2017-09-23 02:20:59] request.INFO: Matched route "_profiler". {"route":"_profiler","route_parameters":{"_controller":"web_profiler.controller.profiler:panelAction","token":"198c55","_route":"_profiler"},"request_uri":"http://127.0.0.1:8000/_profiler/198c55?panel=security","method":"GET"} []
[2017-09-23 02:20:59] request.INFO: Matched route "_profiler_search_bar". {"route":"_profiler_search_bar","route_parameters":{"_controller":"web_profiler.controller.profiler:searchBarAction","_route":"_profiler_search_bar"},"request_uri":"http://127.0.0.1:8000/_profiler/search_bar?panel=security","method":"GET"} []
[2017-09-23 02:57:05] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 02:57:05] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 02:57:05] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"016aa3","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/016aa3","method":"GET"} []
[2017-09-23 02:57:34] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 02:57:34] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:53)"} []
[2017-09-23 02:57:34] security.DEBUG: Calling Authentication entry point. [] []
[2017-09-23 02:57:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "login" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 46 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"login\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:46)"} []
[2017-09-23 02:57:34] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"03cb94","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/03cb94","method":"GET"} []
[2017-09-23 02:57:34] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:53)"} []
[2017-09-23 02:57:34] security.DEBUG: Calling Authentication entry point. [] []
[2017-09-23 02:57:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "login" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 46 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"login\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:46)"} []
[2017-09-23 02:57:45] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 02:57:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 02:57:45] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"5d6afb","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/5d6afb","method":"GET"} []
[2017-09-23 03:29:53] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:29:53] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:31:33] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:31:33] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:34:26] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:34:26] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:36:15] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:36:15] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:37:18] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:37:18] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:37:28] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:37:28] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:38:28] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:38:28] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:41:19] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:41:19] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:44:39] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:44:39] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:46:25] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:46:25] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:48:28] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:48:28] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:48:49] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:48:49] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:49:03] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:49:03] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:49:17] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:49:17] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:51:07] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:51:07] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:51:17] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:51:17] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:54:37] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 03:54:37] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:55:01] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 03:55:01] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:55:15] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 03:55:15] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:00:27] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 04:00:27] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:01:46] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 04:01:46] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:02:53] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:02:53] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:04:10] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:04:10] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:06:49] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:06:50] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:08:32] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:08:32] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:10:15] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:10:15] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:10:38] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:10:38] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:07] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:11:07] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:18] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-09-23 04:11:18] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:34] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:55] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:12:19] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:12:19] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:13:34] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:13:34] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
