[2017-09-23 01:48:31] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-09-23 01:54:03] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServer.php\",\"line\":132,\"trace\":[{\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php\",\"line\":136,\"function\":\"isRunning\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServer\",\"type\":\"->\"}],\"count\":1})"} []
[2017-09-23 01:54:17] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 01:54:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 01:54:17] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"198c55","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/198c55","method":"GET"} []
[2017-09-23 02:20:59] request.INFO: Matched route "_profiler". {"route":"_profiler","route_parameters":{"_controller":"web_profiler.controller.profiler:panelAction","token":"198c55","_route":"_profiler"},"request_uri":"http://127.0.0.1:8000/_profiler/198c55?panel=security","method":"GET"} []
[2017-09-23 02:20:59] request.INFO: Matched route "_profiler_search_bar". {"route":"_profiler_search_bar","route_parameters":{"_controller":"web_profiler.controller.profiler:searchBarAction","_route":"_profiler_search_bar"},"request_uri":"http://127.0.0.1:8000/_profiler/search_bar?panel=security","method":"GET"} []
[2017-09-23 02:57:05] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 02:57:05] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 02:57:05] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"016aa3","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/016aa3","method":"GET"} []
[2017-09-23 02:57:34] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 02:57:34] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:53)"} []
[2017-09-23 02:57:34] security.DEBUG: Calling Authentication entry point. [] []
[2017-09-23 02:57:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "login" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 46 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"login\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:46)"} []
[2017-09-23 02:57:34] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"03cb94","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/03cb94","method":"GET"} []
[2017-09-23 02:57:34] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:53)"} []
[2017-09-23 02:57:34] security.DEBUG: Calling Authentication entry point. [] []
[2017-09-23 02:57:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "login" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 46 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"login\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:46)"} []
[2017-09-23 02:57:45] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 02:57:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 02:57:45] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"5d6afb","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/5d6afb","method":"GET"} []
[2017-09-23 03:29:53] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:29:53] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:31:33] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:31:33] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:34:26] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:34:26] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:36:15] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:36:15] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:37:18] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:37:18] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:37:28] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:37:28] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:38:28] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:38:28] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:41:19] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:41:19] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:44:39] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:44:39] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:46:25] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:46:25] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:48:28] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:48:28] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:48:49] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:48:49] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:49:03] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:49:03] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:49:17] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.64' (using password: YES)"} []
[2017-09-23 03:49:17] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:51:07] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:51:07] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:51:17] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 03:51:17] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:54:37] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 03:54:37] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:55:01] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 03:55:01] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 03:55:15] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 03:55:15] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:00:27] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 04:00:27] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:01:46] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'89.47.15.173' (using password: YES)"} []
[2017-09-23 04:01:46] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:02:53] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:02:53] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:04:10] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:04:10] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:06:49] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:06:50] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:08:32] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:08:32] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:10:15] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:10:15] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:10:38] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:10:38] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:07] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:11:07] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:18] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-09-23 04:11:18] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:34] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:11:55] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:12:19] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:12:19] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:13:34] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:13:34] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:22:24] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'117.136.38.57' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'117.136.38.57' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'117.136.38.57' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'117.136.38.57' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'117.136.38.57' (using password: YES)"} []
[2017-09-23 04:22:24] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:22:46] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.134' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.134' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.134' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.134' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.134' (using password: YES)"} []
[2017-09-23 04:22:46] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:23:16] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:23:16] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:23:25] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES) at /var/www/html/Capa_dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'104.237.91.161' (using password: YES)"} []
[2017-09-23 04:23:25] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:24:21] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-09-23 04:28:48] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServer.php\",\"line\":132,\"trace\":[{\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php\",\"line\":136,\"function\":\"isRunning\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServer\",\"type\":\"->\"}],\"count\":1})"} []
[2017-09-23 04:28:50] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 04:28:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:28:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"2af022","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/2af022","method":"GET"} []
[2017-09-23 04:31:27] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 04:31:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:31:27] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"c43c24","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/c43c24","method":"GET"} []
[2017-09-23 04:31:32] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:31:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:31:32] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/login" is not callable. Expected method "loginAction" on class "AppBundle\Controller\DefaultController". Available methods: "indexAction", "setContainer"." at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php line 98 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/login\" is not callable. Expected method \"loginAction\" on class \"AppBundle\\Controller\\DefaultController\". Available methods: \"indexAction\", \"setContainer\". at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:98)"} []
[2017-09-23 04:31:32] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"6a2ed9","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/6a2ed9","method":"GET"} []
[2017-09-23 04:32:04] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:32:04] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:32:04] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/login" is not callable. Expected method "loginAction" on class "AppBundle\Controller\DefaultController". Available methods: "indexAction", "login", "setContainer"." at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php line 98 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/login\" is not callable. Expected method \"loginAction\" on class \"AppBundle\\Controller\\DefaultController\". Available methods: \"indexAction\", \"login\", \"setContainer\". at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php:98)"} []
[2017-09-23 04:32:05] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"4430c9","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/4430c9","method":"GET"} []
[2017-09-23 04:32:17] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:32:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:32:17] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"a3024b","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/a3024b","method":"GET"} []
[2017-09-23 04:36:06] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "The routing file "/var/www/html/Capa_dev/app/config/routing.yml" must not specify both the "resource" key and the "path" key for "app". Choose between an import and a route definition in /var/www/html/Capa_dev/app/config/routing.yml (which is being imported from "/var/www/html/Capa_dev/app/config/routing_dev.yml")." at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 179 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): The routing file \"/var/www/html/Capa_dev/app/config/routing.yml\" must not specify both the \"resource\" key and the \"path\" key for \"app\". Choose between an import and a route definition in /var/www/html/Capa_dev/app/config/routing.yml (which is being imported from \"/var/www/html/Capa_dev/app/config/routing_dev.yml\"). at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:179, InvalidArgumentException(code: 0): The routing file \"/var/www/html/Capa_dev/app/config/routing.yml\" must not specify both the \"resource\" key and the \"path\" key for \"app\". Choose between an import and a route definition. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:190)"} []
[2017-09-23 04:36:14] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "The "type" key for the route definition "app" in "/var/www/html/Capa_dev/app/config/routing.yml" is unsupported. It is only available for imports in combination with the "resource" key in /var/www/html/Capa_dev/app/config/routing.yml (which is being imported from "/var/www/html/Capa_dev/app/config/routing_dev.yml")." at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 179 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): The \"type\" key for the route definition \"app\" in \"/var/www/html/Capa_dev/app/config/routing.yml\" is unsupported. It is only available for imports in combination with the \"resource\" key in /var/www/html/Capa_dev/app/config/routing.yml (which is being imported from \"/var/www/html/Capa_dev/app/config/routing_dev.yml\"). at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:179, InvalidArgumentException(code: 0): The \"type\" key for the route definition \"app\" in \"/var/www/html/Capa_dev/app/config/routing.yml\" is unsupported. It is only available for imports in combination with the \"resource\" key. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:196)"} []
[2017-09-23 04:37:01] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 04:37:01] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:37:01] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b7d226","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/b7d226","method":"GET"} []
[2017-09-23 04:37:37] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:37:37] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:37:37] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Unable to find template "OCUserBundle:Security:login.html.twig" (looked into: /var/www/html/Capa_dev/app/Resources/views, /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form)." at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 127 {"exception":"[object] (InvalidArgumentException(code: 0): Unable to find template \"OCUserBundle:Security:login.html.twig\" (looked into: /var/www/html/Capa_dev/app/Resources/views, /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form). at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php:127, Twig_Error_Loader(code: 0): Unable to find template \"OCUserBundle:Security:login.html.twig\" (looked into: /var/www/html/Capa_dev/app/Resources/views, /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form). at /var/www/html/Capa_dev/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:232)"} []
[2017-09-23 04:37:38] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b1e7a7","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/b1e7a7","method":"GET"} []
[2017-09-23 04:39:11] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:39:11] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:39:11] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"5029a9","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/5029a9","method":"GET"} []
[2017-09-23 04:43:45] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:43:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:43:48] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:43:48] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:43:48] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"81af6f","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/81af6f","method":"GET"} []
[2017-09-23 04:44:32] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:44:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:44:32] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"6ee476","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/6ee476","method":"GET"} []
[2017-09-23 04:45:42] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:45:42] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:45:42] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Variable "error" does not exist." at /var/www/html/Capa_dev/app/Resources/views/default/login.html.twig line 6 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"error\" does not exist. at /var/www/html/Capa_dev/app/Resources/views/default/login.html.twig:6)"} []
[2017-09-23 04:45:42] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"32c07f","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/32c07f","method":"GET"} []
[2017-09-23 04:46:05] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:46:05] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:46:05] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Variable "last_username" does not exist." at /var/www/html/Capa_dev/app/Resources/views/default/login.html.twig line 10 {"exception":"[object] (Twig_Error_Runtime(code: 0): Variable \"last_username\" does not exist. at /var/www/html/Capa_dev/app/Resources/views/default/login.html.twig:10)"} []
[2017-09-23 04:46:05] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"c16419","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/c16419","method":"GET"} []
[2017-09-23 04:48:37] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:48:37] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:48:52] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:48:52] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:48:52] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:48:52] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:48:52] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:48:53] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:48:53] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:48:53] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:48:53] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:48:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:48:54] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:48:54] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:48:54] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:48:54] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:48:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:48:54] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:48:54] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:48:54] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:48:54] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:48:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:48:55] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:48:55] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:48:55] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:48:55] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:48:55] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:49:13] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:49:13] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:49:13] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:49:13] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:49:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:49:13] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:49:13] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:49:13] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:49:13] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:49:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:49:13] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:49:13] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:49:13] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:49:14] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:49:14] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:49:14] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:49:14] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:49:14] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:49:14] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:49:14] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:49:14] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:49:14] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 04:49:14] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 04:49:14] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:49:14] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 04:49:31] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 04:49:31] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-23 04:49:31] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:49:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 04:49:31] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"537da3","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/537da3","method":"GET"} []
[2017-09-23 04:52:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 04:52:39] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"615aba","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/615aba","method":"GET"} []
[2017-09-23 04:53:01] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:53:01] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:53:01] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:53:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "default" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 49 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"default\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:49)"} []
[2017-09-23 04:53:01] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:53:02] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"a2a277","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/a2a277","method":"GET"} []
[2017-09-23 04:54:33] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:54:33] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:54:33] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:54:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "default" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 49 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"default\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:49)"} []
[2017-09-23 04:54:33] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:54:33] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"86e374","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/86e374","method":"GET"} []
[2017-09-23 04:54:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 04:54:57] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"cb723b","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/cb723b","method":"GET"} []
[2017-09-23 04:55:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 04:55:37] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"5d855c","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/5d855c","method":"GET"} []
[2017-09-23 04:55:46] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 04:55:46] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:55:46] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:55:46] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:55:46] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"71d001","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/71d001","method":"GET"} []
[2017-09-23 04:57:03] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 04:57:03] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:57:03] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:57:03] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:57:03] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"599dad","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/599dad","method":"GET"} []
[2017-09-23 04:57:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 04:57:09] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"88c4d3","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/88c4d3","method":"GET"} []
[2017-09-23 04:58:06] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:58:06] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:58:06] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:58:06] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: authenticationUtils" at /var/www/html/Capa_dev/src/AppBundle/Controller/DefaultController.php line 35 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined variable: authenticationUtils at /var/www/html/Capa_dev/src/AppBundle/Controller/DefaultController.php:35)"} []
[2017-09-23 04:58:06] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:58:06] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"787cc6","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/787cc6","method":"GET"} []
[2017-09-23 04:58:07] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:58:07] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:58:07] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:58:07] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined variable: authenticationUtils" at /var/www/html/Capa_dev/src/AppBundle/Controller/DefaultController.php line 35 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined variable: authenticationUtils at /var/www/html/Capa_dev/src/AppBundle/Controller/DefaultController.php:35)"} []
[2017-09-23 04:58:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:58:08] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"cef597","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/cef597","method":"GET"} []
[2017-09-23 04:58:31] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:58:31] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:58:31] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:58:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "default" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 49 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"default\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:49)"} []
[2017-09-23 04:58:31] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:58:31] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"c56c58","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/c56c58","method":"GET"} []
[2017-09-23 04:58:58] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:58:58] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:58:58] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:58:58] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "default" as such route does not exist." at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 49 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"default\" as such route does not exist. at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:49)"} []
[2017-09-23 04:58:58] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:58:58] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"f99b80","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/f99b80","method":"GET"} []
[2017-09-23 04:59:24] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 04:59:24] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:59:24] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:59:24] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:59:24] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"fbefba","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/fbefba","method":"GET"} []
[2017-09-23 04:59:55] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 04:59:55] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:59:55] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:59:55] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:59:55] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 04:59:55] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 04:59:55] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 04:59:55] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 04:59:55] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"4014b0","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/4014b0","method":"GET"} []
[2017-09-23 05:00:04] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:00:04] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:00:04] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:00:04] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:00:04] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 05:00:04] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:00:04] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:00:04] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:00:04] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"1d7592","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/1d7592","method":"GET"} []
[2017-09-23 05:02:33] request.INFO: Matched route "logout". {"route":"logout","route_parameters":{"_route":"logout"},"request_uri":"http://127.0.0.1:8000/logout","method":"GET"} []
[2017-09-23 05:02:33] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:02:33] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:02:33] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:02:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:02:36] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:02:36] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"dzadaz\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 05:02:36] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 05:02:36] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:02:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:02:41] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:02:41] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"azdazdaz\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 05:02:41] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 05:02:41] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:02:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:02:47] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:02:47] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-23 05:02:47] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:02:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:02:47] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"85e15d","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/85e15d","method":"GET"} []
[2017-09-23 05:02:47] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:02:47] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:02:47] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:03:03] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:03:03] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:03:03] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:03:03] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:03:03] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 05:03:03] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:03:03] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:03:03] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:03:03] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"4d7313","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/4d7313","method":"GET"} []
[2017-09-23 05:03:03] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:03:03] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:03:03] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:03:40] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:03:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:03:40] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:03:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:03:40] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 05:03:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:03:40] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:03:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:03:40] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"0b293a","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/0b293a","method":"GET"} []
[2017-09-23 05:03:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:03:40] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:03:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:02] request.INFO: Matched route "logout". {"route":"logout","route_parameters":{"_route":"logout"},"request_uri":"http://127.0.0.1:8000/logout","method":"GET"} []
[2017-09-23 05:06:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:02] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:02] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:06:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:06:05] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:06:05] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"anna_admin\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-23 05:06:05] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 05:06:05] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:06:05] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:06:12] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:06:12] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:90, Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): The presented password is invalid. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:67)"} []
[2017-09-23 05:06:12] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-23 05:06:12] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:06:12] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:06:21] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:06:21] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-23 05:06:21] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:21] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:06:21] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"866099","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/866099","method":"GET"} []
[2017-09-23 05:06:21] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:21] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:21] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:40] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:06:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:40] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:40] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 05:06:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:40] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:40] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"11a5a1","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/11a5a1","method":"GET"} []
[2017-09-23 05:06:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:40] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:40] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:06:49] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"af52b2","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/af52b2","method":"GET"} []
[2017-09-23 05:06:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:49] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:06:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"844aeb","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/844aeb","method":"GET"} []
[2017-09-23 05:06:50] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:50] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:50] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:50] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:06:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"9a52ff","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/9a52ff","method":"GET"} []
[2017-09-23 05:06:50] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:50] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:50] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:50] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:06:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"6570b8","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/6570b8","method":"GET"} []
[2017-09-23 05:06:50] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:50] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:50] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:06:51] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"409ba8","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/409ba8","method":"GET"} []
[2017-09-23 05:06:51] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:51] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:51] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:06:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:06:51] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"31e232","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/31e232","method":"GET"} []
[2017-09-23 05:06:51] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:06:51] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:06:51] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:08:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:08:55] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"ea4fd5","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/ea4fd5","method":"GET"} []
[2017-09-23 05:08:55] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:08:55] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:08:55] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:08:59] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 05:08:59] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:08:59] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:08:59] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:08:59] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e4e991","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/e4e991","method":"GET"} []
[2017-09-23 05:08:59] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:08:59] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:08:59] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:09:02] request.INFO: Matched route "logout". {"route":"logout","route_parameters":{"_route":"logout"},"request_uri":"http://127.0.0.1:8000/logout","method":"GET"} []
[2017-09-23 05:09:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:09:02] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:09:02] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:09:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:09:08] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:09:08] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-23 05:09:08] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:09:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:09:09] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"f7c436","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/f7c436","method":"GET"} []
[2017-09-23 05:09:09] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:09:09] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:09:09] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:14:17] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:14:17] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:14:17] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:14:17] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:14:17] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 05:14:17] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:14:17] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:14:17] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:14:17] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"bac80e","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/bac80e","method":"GET"} []
[2017-09-23 05:14:17] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:14:17] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:14:17] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:14:21] request.INFO: Matched route "logout". {"route":"logout","route_parameters":{"_route":"logout"},"request_uri":"http://127.0.0.1:8000/logout","method":"GET"} []
[2017-09-23 05:14:21] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:14:21] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:14:21] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:14:21] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:18:05] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:18:05] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-23 05:18:05] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:18:05] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:18:06] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"f03726","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/f03726","method":"GET"} []
[2017-09-23 05:18:06] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:18:06] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:18:06] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:20:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:20:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"757f7b","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/757f7b","method":"GET"} []
[2017-09-23 05:20:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:20:00] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:20:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:20:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:20:01] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"9a2171","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/9a2171","method":"GET"} []
[2017-09-23 05:20:01] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:20:01] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:20:01] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:20:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:20:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:20:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:20:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://127.0.0.1:8000/login")" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://127.0.0.1:8000/login\") at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:134)"} []
[2017-09-23 05:20:02] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"80762a","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/80762a","method":"GET"} []
[2017-09-23 05:20:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:20:02] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:20:02] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:18] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:21:18] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:18] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:18] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:18] request.INFO: Matched route "app". {"route":"app","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"app"},"request_uri":"http://127.0.0.1:8000/default","method":"GET"} []
[2017-09-23 05:21:18] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:18] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:18] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:18] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"04ff77","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/04ff77","method":"GET"} []
[2017-09-23 05:21:18] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:18] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:18] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:23] request.INFO: Matched route "logout". {"route":"logout","route_parameters":{"_route":"logout"},"request_uri":"http://127.0.0.1:8000/logout","method":"GET"} []
[2017-09-23 05:21:23] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:23] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:23] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:21:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:21:34] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:21:34] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-23 05:21:34] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:34] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 05:21:34] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:34] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:34] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:34] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b79376","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/b79376","method":"GET"} []
[2017-09-23 05:21:34] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:34] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:34] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:42] request.INFO: Matched route "logout". {"route":"logout","route_parameters":{"_route":"logout"},"request_uri":"http://127.0.0.1:8000/logout","method":"GET"} []
[2017-09-23 05:21:42] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:42] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:42] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-23 05:21:42] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-23 05:21:45] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-23 05:21:45] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-23 05:21:45] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:45] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-23 05:21:45] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:45] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:45] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-23 05:21:45] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"6788b6","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/6788b6","method":"GET"} []
[2017-09-23 05:21:45] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-23 05:21:45] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-23 05:21:45] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:02:03] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-24 03:02:03] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:02:03] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:02:03] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:02:03] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"7ca176","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/7ca176","method":"GET"} []
[2017-09-24 03:02:03] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:02:03] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:02:04] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:13:39] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-09-24 03:13:39] console.DEBUG: Command "doctrine:schema:update" exited with code "1" {"command":"doctrine:schema:update","code":1} []
[2017-09-24 03:13:55] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-09-24 03:13:55] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-09-24 03:13:55] doctrine.DEBUG: CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-09-24 03:38:29] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-24 03:38:29] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:38:29] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:38:29] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:38:29] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e579a9","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/e579a9","method":"GET"} []
[2017-09-24 03:38:29] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:38:29] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:38:29] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:38:29] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-24 03:38:29] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:38:29] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:38:29] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:38:29] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"aa85cf","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/aa85cf","method":"GET"} []
[2017-09-24 03:38:29] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:38:29] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:38:29] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:38:30] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-24 03:38:30] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:38:30] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:38:30] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 03:38:30] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"426399","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/426399","method":"GET"} []
[2017-09-24 03:38:30] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-24 03:38:30] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-24 03:38:30] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-24 05:20:44] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServer.php\",\"line\":132,\"trace\":[{\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php\",\"line\":136,\"function\":\"isRunning\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServer\",\"type\":\"->\"}],\"count\":1})"} []
[2017-09-27 04:04:26] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServer.php\",\"line\":132,\"trace\":[{\"file\":\"/var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/Command/ServerStartCommand.php\",\"line\":136,\"function\":\"isRunning\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServer\",\"type\":\"->\"}],\"count\":1})"} []
[2017-09-27 04:04:39] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-27 04:04:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:04:40] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"9af2ab","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/9af2ab","method":"GET"} []
[2017-09-27 04:04:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:04:43] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-27 04:04:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:04:43] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e2bf73","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/e2bf73","method":"GET"} []
[2017-09-27 04:04:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:05:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login.html"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login.html\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-09-27 04:05:04] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"667249","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/667249","method":"GET"} []
[2017-09-27 04:05:04] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:05:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login.php"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login.php\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-09-27 04:05:07] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"22cf3d","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/22cf3d","method":"GET"} []
[2017-09-27 04:05:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:06:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login.html"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login.html\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-09-27 04:06:06] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"8c2e62","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/8c2e62","method":"GET"} []
[2017-09-27 04:06:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:06:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login.html.twig"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login.html.twig\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-09-27 04:06:19] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"a2b865","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/a2b865","method":"GET"} []
[2017-09-27 04:06:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:06:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /login.html"" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /login.html\" at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/Capa_dev/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-09-27 04:06:23] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"ce6680","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/ce6680","method":"GET"} []
[2017-09-27 04:06:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:06:33] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:06:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:11:36] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:11:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:11:48] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-27 04:11:48] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"NONE_PROVIDED\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-27 04:11:48] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-27 04:11:49] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:11:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:12:31] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:12:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:12:43] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-27 04:12:43] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:90, Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): The presented password is invalid. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:67)"} []
[2017-09-27 04:12:43] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-27 04:12:43] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:12:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:13:07] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-27 04:13:07] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-27 04:13:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-27 04:13:07] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-27 04:13:07] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-27 04:13:07] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-27 04:13:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-27 04:13:07] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b67f9e","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/b67f9e","method":"GET"} []
[2017-09-27 04:13:07] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-27 04:13:07] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-27 04:13:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-27 04:13:29] request.INFO: Matched route "logout". {"route":"logout","route_parameters":{"_route":"logout"},"request_uri":"http://127.0.0.1:8000/logout","method":"GET"} []
[2017-09-27 04:13:29] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-27 04:13:29] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-27 04:13:29] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:13:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:13:38] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-27 04:13:38] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"NONE_PROVIDED\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-27 04:13:38] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-27 04:13:38] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:13:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:13:45] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-27 04:13:45] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"NONE_PROVIDED\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-27 04:13:45] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-27 04:13:45] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:13:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:13:53] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-27 04:13:53] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"NONE_PROVIDED\" does not exist. at /var/www/html/Capa_dev/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php:109)"} []
[2017-09-27 04:13:53] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"login"} []
[2017-09-27 04:13:53] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:13:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:14:01] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::loginAction","_route":"login"},"request_uri":"http://127.0.0.1:8000/login","method":"GET"} []
[2017-09-27 04:14:01] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-27 04:14:07] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1:8000/login_check","method":"POST"} []
[2017-09-27 04:14:07] security.INFO: User has been authenticated successfully. {"username":"user"} []
[2017-09-27 04:14:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-27 04:14:07] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"home"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-09-27 04:14:07] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-27 04:14:07] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-27 04:14:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-27 04:14:07] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"460d91","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/460d91","method":"GET"} []
[2017-09-27 04:14:07] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-27 04:14:07] security.DEBUG: User was reloaded from a user provider. {"username":"user","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-09-27 04:14:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
